services:
  movies:
    build: ./app/
    image: movies_cloud
    container_name: movies_cloud
    ports:
      - "8000:8000"
    volumes:
      - ./app:/home/app
    env_file:
      - ./app/.env
  chat-ui:
    build: ./ui/
    image: chat-ui-streamlit
    container_name: chat_ui
    ports:
      - "8501:8501"
    environment:
      - ENDPOINT_BASE_URL=https://movies-bhdshhgwexfegggf.canadacentral-01.azurewebsites.net/api/v1
      - TMDB_API_KEY=0d7b40f3c01f3671491c71a5983d9db9